# Use an official Node.js runtime as a parent image

FROM node:21-alpine AS builder
ENV NODE_ENV production

# Set the working directory to /app

WORKDIR /app

# Cache and Install dependencies

COPY package.json .
RUN npm i

# Copy the rest of the application code to the working directory

COPY . .

ARG REACT_APP_ENDPOINT
RUN sh create-env-file.sh REACT_APP_ENDPOINT=$REACT_APP_ENDPOINT
RUN echo $REACT_APP_ENDPOINT

# Build the app

RUN npm run build

# Bundle static assets with nginx

FROM nginx:1.21.0-alpine as production
ENV NODE_ENV production

# Copy built assets from builder

COPY --from=builder /app/build /usr/share/nginx/html

# Add your nginx.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port

EXPOSE 80

# Start nginx

CMD ["nginx", "-g", "daemon off;"]
