version: '3.8'

services:
  #regcam:
  #  build: .
  #  image: psychotropia/regcam
  mysql:
    image: mysql:latest
    environment:
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: regcam
      MYSQL_CHARSET: utf8mb4
    container_name: regcam_mysql
    expose:
      - 3306
    networks:
      - red_internal
    volumes:
      - ./regcamDUMP.sql:/docker-entrypoint-initdb.d/regcamDUMP.sql #dump db
      - dataregcam:/var/lib/mysql #donde se guardara data
      #- ./create-user.sql:/docker-entrypoint-initdb.d/create-user.sql
    #preguntarle al profe
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    expose: 
      - 80
    depends_on:
      - mysql
    environment:
      VIRTUAL_HOST: api.regcam.informatica.uv.cl
      CORS_ORIGIN: http://regcam.informatica.uv.cl
      NODE_ENV: production
      MYSQL_HOST: regcam_mysql
      MYSQL_PORT: 3306
      MYSQL_USER: admin
      MYSQL_PASS: password
      MYSQL_DB: regcam
    container_name: backend
    networks:
      - red_proxy
      - red_internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
      args:
        REACT_APP_ENDPOINT: http://api.regcam.informatica.uv.cl
    expose: 
      - 80
    environment:
      VIRTUAL_HOST: regcam.informatica.uv.cl
      REACT_APP_ENDPOINT: http://api.regcam.informatica.uv.cl
    depends_on:
      - backend
    container_name: frontend
    networks:
      - red_proxy
      - red_internal


networks:
  red_proxy:
    external:
      name: network-docker
  red_internal:

volumes:
  dataregcam:

    
