# Use an official Node.js runtime as a parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Install MySQL client
RUN apt-get update && apt-get install -y mariadb-client

# Expose the port the app runs on
EXPOSE 3001

# Define environment variables
ENV NODE_ENV=production

# Command to run your application
CMD ["node", "index.js"]